In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
def sl_():
    print('-'*50)

## 数组

In [2]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]
sl_()

fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]
sl_()

floats2 == floats

0.09366074898062304

--------------------------------------------------


0.09366074898062304

--------------------------------------------------


True

## 内存视图

In [3]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)
sl_()

memv[0]
sl_()

memv_oct = memv.cast('B')
memv_oct.tolist()
sl_()

memv_oct[5] = 4
numbers

5

--------------------------------------------------


-2

--------------------------------------------------


[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

--------------------------------------------------


array('h', [-2, -1, 1024, 1, 2])

## Numpy, Scipy

In [4]:
import numpy as np

a = np.arange(12)
a
sl_()

type(a)
sl_()

a.shape
sl_()

a.shape = 3, 4
a
sl_()

a[2]
sl_()

a[2, 1]
sl_()

a[:, 1]
sl_()

a.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

--------------------------------------------------


numpy.ndarray

--------------------------------------------------


(12,)

--------------------------------------------------


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

--------------------------------------------------


array([ 8,  9, 10, 11])

--------------------------------------------------


9

--------------------------------------------------


array([1, 5, 9])

--------------------------------------------------


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [5]:
import numpy as np

# floats = np.loadtxt('floats-10M-lines.txt')
floats = np.array([random() for _ in range(10)])
floats[-3:]
sl_()

floats *= .5
floats[-3:]
sl_()

from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0
sl_()

np.save('floats-10M', floats)
floats2 = np.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]

array([ 0.91472865,  0.17472736,  0.59330209])

--------------------------------------------------


array([ 0.45736432,  0.08736368,  0.29665104])

--------------------------------------------------


0.00010183002450503409

--------------------------------------------------


memmap([ 0.91472865,  0.17472736,  0.59330209])

## deque

In [6]:
from collections import deque

dq = deque(range(10), maxlen=10)
dq
sl_()

dq.rotate(3)
dq
sl_()

dq.rotate(-4)
dq
sl_()

dq.appendleft(-1)
dq
sl_()

dq.extend([11, 22, 33])
dq
sl_()

dq.extendleft([10, 20, 30, 40])
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

--------------------------------------------------


deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

--------------------------------------------------


deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

--------------------------------------------------


deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

--------------------------------------------------


deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

--------------------------------------------------


deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])